

# Settings for the init image
init:
  image:
    repository: test/galaxy-sc-tertiary
    tag: "19.05-dev"
    pullPolicy: IfNotPresent
  force_copy: "__venv__,__config__,__galaxy-central__,__tools__"

image:
  repository: quay.io/bgruening/galaxy-web
  tag: "dev"
  pullPolicy: Always

admin:
  email: admin@email.co.uk
  password: "change-me"
  api_key: askdhaskjdhqwkdnqdq
  username: admin

galaxy_conf:
  brand: "scRNA-Seq Tertiary A."
  admin_users: admin@email.co.uk
  allow_user_creation: true
  allow_user_deletion: true
  cleanup_job: never
  enable_beta_mulled_containers: true


job_conf:
  runners:
    enable_local: "true"
    enable_k8: "true"
    k8s_persistent_volume_claims: "galaxy-pvc:/export"
  destinations:
    default: "docker_dispatch"
    docker_default: "k8s_default"
    no_docker_default: "local_no_container"


persistence:
  # storageClass: "-"
  minikube:
    enabled: false
    # hostPath: "/data/galaxy-18.05-tertiary"

service:
  type: NodePort

ingress:
  enabled: false


postgresql:
  image: "quay.io/bgruening/galaxy-postgres"
  imageTag: "dev"
  persistence:
    subPath: "postgres-tertiary-19.05-dev"

proftpd:
  image:
    repository: "quay.io/bgruening/galaxy-proftpd"
    tag: "dev"
  service:
    type: NodePort

rbac:
  enabled: true
