install_resolver_dependencies: true
install_tool_dependencies: false
tools:
  - name: dropletutils_read_10x
    owner: ebi-gxa
    revisions:
    - d62a9aa0411e
    tool_panel_section_id: ''
    tool_panel_section_label: ''
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: gtf2gene_list
    owner: ebi-gxa
    revisions:
    - 040d4b3a19d5
    - f97b7ba180b4
    tool_panel_section_id: util
    tool_panel_section_label: Util
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: retrieve_scxa
    owner: ebi-gxa
    revisions:
    - cd6b80f62fcc
    tool_panel_section_id: atlas
    tool_panel_section_label: 'Expression Atlas'
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: sc3_calc_biology
    owner: ebi-gxa
    revisions:
    - 2ee3dd245f72
    tool_panel_section_id: sc3-prod
    tool_panel_section_label: SC3-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: sc3_calc_consens
    owner: ebi-gxa
    revisions:
    - aa83350751f5
    tool_panel_section_id: sc3-prod
    tool_panel_section_label: SC3-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: sc3_calc_dists
    owner: ebi-gxa
    revisions:
    - d005fe979d80
    tool_panel_section_id: sc3-prod
    tool_panel_section_label: SC3-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: sc3_calc_transfs
    owner: ebi-gxa
    revisions:
    - b06019da7b5a
    tool_panel_section_id: sc3-prod
    tool_panel_section_label: SC3-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: sc3_estimate_k
    owner: ebi-gxa
    revisions:
    - aab4d3a52ee3
    tool_panel_section_id: sc3-prod
    tool_panel_section_label: SC3-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: sc3_kmeans
    owner: ebi-gxa
    revisions:
    - b3c3cf813a49
    tool_panel_section_id: sc3-prod
    tool_panel_section_label: SC3-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: sc3_prepare
    owner: ebi-gxa
    revisions:
    - 9a2b61bfdaa9
    tool_panel_section_id: sc3-prod
    tool_panel_section_label: SC3-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: scanpy_compute_graph
    owner: ebi-gxa
    revisions:
    - 3d242b0d97d0
    - c3c89fc3095a
    tool_panel_section_id: scanpy-prod
    tool_panel_section_label: Scanpy-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: scanpy_filter_cells
    owner: ebi-gxa
    revisions:
    - 9f0ca1641ab2
    - cad451be0a2a
    tool_panel_section_id: scanpy-prod
    tool_panel_section_label: Scanpy-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: scanpy_find_cluster
    owner: ebi-gxa
    revisions:
    - ce27ae8a36cd
    - 2cb836f82ddb
    tool_panel_section_id: scanpy-prod
    tool_panel_section_label: Scanpy-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: scanpy_normalise_data
    owner: ebi-gxa
    revisions:
    - 1dda36e73482
    - 19805a556cd6
    tool_panel_section_id: scanpy-prod
    tool_panel_section_label: Scanpy-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: scanpy_read_10x
    owner: ebi-gxa
    revisions:
    - 572b6e3b2aff
    - c5e166a64abb
    tool_panel_section_id: scanpy-prod
    tool_panel_section_label: Scanpy-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: seurat_create_seurat_object
    owner: ebi-gxa
    revisions:
    - f8865ae30723
    - 28bf28ee53b6
    tool_panel_section_id: seurat-prod
    tool_panel_section_label: Seurat-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: seurat_find_variable_genes
    owner: ebi-gxa
    revisions:
    - a56efad05337
    - e683206b4f6f
    tool_panel_section_id: seurat-prod
    tool_panel_section_label: Seurat-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: seurat_normalise_data
    owner: ebi-gxa
    revisions:
    - 619fead82856
    - fe2f888644e6
    tool_panel_section_id: seurat-prod
    tool_panel_section_label: Seurat-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: seurat_read10x
    owner: ebi-gxa
    revisions:
    - 1b8566f3c1d0
    - fa4509d3f0aa
    tool_panel_section_id: seurat-prod
    tool_panel_section_label: Seurat-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: seurat_run_tsne
    owner: ebi-gxa
    revisions:
    - 3aea769deab1
    - 221cc4a7ef6e
    tool_panel_section_id: seurat-prod
    tool_panel_section_label: Seurat-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: seurat_scale_data
    owner: ebi-gxa
    revisions:
    - 6166efaeb4a6
    - 7ef152a02e71
    tool_panel_section_id: seurat-prod
    tool_panel_section_label: Seurat-Prod
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: sra_tools
    owner: iuc
    revisions:
    - 5e6237d58b0c
    tool_panel_section_id: rna-seq
    tool_panel_section_label: RNA-Seq
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: text_processing
    owner: bgruening
    revisions:
    - 0a8c6b61f0f4
    tool_panel_section_id: text_manipulation
    tool_panel_section_label: Text manipulation
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: ucsc_cell_browser
    owner: ebi-gxa
    revisions:
    - 1b43a2d812c9
    tool_panel_section_id: ''
    tool_panel_section_label: ''
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
  - name: umi_tools_count
    owner: iuc
    revisions:
    - b557acca0b56
    tool_panel_section_id: rna-seq
    tool_panel_section_label: RNA-Seq
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
# General RNA-Seq
  - name: tophat2
    owner: devteam
    revisions:
    - 16c4255042be
    tool_panel_section_id: rna-seq
    tool_panel_section_label: RNA-Seq
    tool_shed_url: https://toolshed.g2.bx.psu.edu/

# python get_tool_yml_from_gi.py --galaxy <my_galaxy_url> --api-key <my_admin_api_key> --output-file <my_tool_list.yml>
