name: atlas_fastq_provider
owner: ebi-gxa
description: Scripts and utilities for providing fastqs to workflows
long_description: Generic utility to provide FASTQ files for use in pipelines, etc. At the most basic level files can be downloaded from links. For the ENA, there are three methods: FTP (default), SSH and HTTP.
homepage_url: https://github.com/ebi-gene-expression-group/atlas-fastq-provider
remote_repository_url: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/tree/develop/tools/fastq_provider
categories: [Sequence Analysis]
